### PR TITLE
Es6 gulpfile

### PR DESCRIPTION
**Pull request by mtho11**
Get all the ES6 goodness in a our gulpfile as now as well.

### CODE REVIEW

**Comment by mtho11** [comment]
Hmm, still issue with License check even after adding the exclusion to the POM.

[INFO] Checking licenses...
[WARNING] Unknown file extension: /home/travis/build/hawkular/hawkular/console/src/main/scripts/.babelrc

@ammendonca or @ppalaga any suggestions?

**Comment by ammendonca** [comment]
Yeah, what you've changed is relative to checkstyle and not license, license exclusions are below @ https://github.com/hawkular/hawkular/blob/es6-gulpfile/console/pom.xml#L133-L137

**Comment by mtho11** [comment]
D'oh! Checkstyle is not maven license checker. Thanks @ammendonca!

**Comment by mtho11** [comment]
Merged #775

**Pull request merged**
