### PR TITLE
HAWKULAR-610 File chooser for add-deployment only accepts .zip by def…

### PR DESCRIPTION
**Pull request by mtho11**
…ault on some browsers.

### CODE REVIEW

**Comment by mtho11** [comment]
@pilhuhn Looks like the 'application/java-archive' doesn't work either.

**Comment by pilhuhn** [comment]
We should probably just accept everything in the file chooser.

**Comment by mtho11** [comment]
For now, I agree.

**Comment by mtho11** [comment]
I had to move this to #483 because of rebase issues on that branch.

**Pull request closed without merging**
