### PR TITLE
Add JMX topics required by BTM 0.7.3.Final

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by ppalaga** [comment]
@objectiser 5f13ad3 adopts your https://github.com/hawkular/hawkular/pull/869 . I'd close PR#869 if you do not mind.

**Comment by objectiser** [comment]
@ppalaga The standalone.xsl I emailed you also included some infinispan cache entries, that don't appear to be in the PR.

**Comment by ppalaga** [comment]
> The standalone.xsl I emailed you also included some infinispan cache entries

@objectiser Sorry, I have not noticed the attachment. In 144bbe1 , the caches should be there: https://github.com/hawkular/hawkular/commit/144bbe1350c997bb52be808bc74f21db1e8fe32d#diff-5bbdd40b2f1afabf062f3e94e667689cR299

**Comment by ppalaga** [comment]
@jpkrohling could you please review the FP and dist parts of this PR?

@jmazzitelli could you please review the parts of this PR related to agent installer? - esp. could you please check that the download works?

**Comment by ppalaga** [comment]
@jmazzitelli I noticed that `hawkular-wildfly-agent-installer.jar` and `hawkular-wildfly-agent-wf-extension.zip` are served from `standalone/configuration` - is there a particular reason for having them just there? I'd spontaneously say that `standalone/configuration` is not a good location for files like that - esp. because `standalone/configuration` is a directory where the user is allowed whatever he likes and the patching mech cannot overwrite the files there without worries. Wouldn't `nest/deployments` be a better place for those files?

**Comment by jpkrohling** [comment]
Looks good to me!

**Comment by jmazzitelli** [comment]
@ppalaga  I just put them there because it was easy for the download servlet to know where to find them. If you look at:

https://github.com/hawkular/hawkular/blob/master/modules/hawkular-wildfly-agent-download/src/main/java/org/hawkular/component/wildflymonitor/WildFlyAgentServlet.java#L490-L509

you will see it just examines the system property "jboss.server.config.dir" (which is a standard WildFly system property) to know where to look for the files.

If we want them somewhere else, we would just modify those two methods so it looks for the files in another location. Not too hard to do, just have to figure out a way to reliably find the directory where those files would be (probably something like "jboss.server.home.dir" + &lt;...path from /modules down to the hawkular nest directory...>).

**Comment by jmazzitelli** [comment]
@ppalaga  I built and ran the distro and the agent is deployed and running fine. I see data in the UI coming from the agent.

**Comment by ppalaga** [comment]
>  I see data in the UI coming from the agent.

Great, thanks a lot, @jmazzitelli !

**Comment by objectiser** [comment]
@ppalaga The latest BTM release will also require a new JMS topic:
                <jms-topic entries="java:/BTxnCompletionInformation" name="BTxnCompletionInformation"/>
I'll release BTM now and add another comment when the new version is ready.

**Comment by objectiser** [comment]
@ppalaga BTM 0.7.4.Final now available - so just requires the additional JMS topic 'BTxnCompletionInformation'.

**Pull request merged**
