### PR TITLE
HAWKULAR-269 - Using jboss.bind.address for KC server URL

### PR DESCRIPTION
**Pull request by jpkrohling**
@theute  , could you please review this one? If approved, I'll also merge the following, as the changes are identical: https://github.com/hawkular/hawkular-accounts/pull/27

### CODE REVIEW

**Comment by theute** [comment]
I am not sure to be the correct reviewer, I was hoping that it would fix the issue when binding to an IP and I get the spinners forever for availability and response time but that makes no difference.

Basically before and after this change I see no difference in what I tried

**Comment by jpkrohling** [comment]
The PR should fix only the accounts part of the problem. So, in the logs you should not see anymore a "failed to retrieve public key" or related issues if you start the server with "-b specific_ip". Although you might still see it if the server is starting up or shutting down.

**Comment by pilhuhn** [comment]
@theute What spinners do you actually mean here?

**Comment by theute** [comment]
@pilhuhn I think it's unrelated. When I bind to some IP, the availability and response time would keep display the waiting image without a value forever, I think this was fixed in some other commit but I didn't check

**Comment by pilhuhn** [comment]
Ok, the spinners are not (no longer?) an issue with recent master and after HAWKULAR-106 ( #158 ) was merged into it.

**Comment by ppalaga** [comment]
This fix is still needed, even after #158 . @pilhuhn could you please merge it?

**Pull request merged**
