### PR TITLE
Bring in update datasources support through upgrading agent and cmdgw to newest 

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by ppalaga** [comment]
@ammendonca a present for you!

**Comment by ammendonca** [comment]
Thanks!

**Comment by ppalaga** [comment]
`UpdateDatasourceRequest` is basically the same as `AddDatasourceRequest` https://github.com/hawkular/hawkular-command-gateway/blob/master/hawkular-command-gateway-api/src/main/resources/schema/UpdateDatasourceRequest.schema.json 
Just note that the `isXa` value is computed from the resource path in `UpdateDatasourceCommand`  rather than read from `boolean xaDatasource` field submitted in the request: https://github.com/hawkular/hawkular-agent/blob/master/hawkular-wildfly-monitor/src/main/java/org/hawkular/agent/monitor/cmd/UpdateDatasourceCommand.java#L93
Si in UI, you do not need to set `UpdateDatasourceRequest.xaDatasource`.

itests: https://github.com/hawkular/hawkular-agent/blob/master/hawkular-agent-itest-parent/hawkular-agent-itest/src/test/java/org/hawkular/cmdgw/ws/test/DatasourceCommandITest.java#L321

and https://github.com/hawkular/hawkular-agent/blob/master/hawkular-agent-itest-parent/hawkular-agent-itest/src/test/java/org/hawkular/cmdgw/ws/test/DatasourceCommandITest.java#L392

Good luck!

**Comment by ppalaga** [comment]
Update Driver will follow soon hopefully

**Pull request merged**
