### PR TITLE
Upgrade to Metrics 0.11.0.Final

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by ppalaga** [comment]
@jsanda here locally, this has failed on `/hawkular/metrics/status` returning `Not Found`. Could you or somebody from metrics have a look what is wrong?

**Comment by stefannegrea** [comment]
@ppalaga, Hawkular Metrics has automated tests for the `status` endpoint: [StatusITest.groovy](https://github.com/hawkular/hawkular-metrics/blob/master/integration-tests/rest-tests-jaxrs/src/test/groovy/org/hawkular/metrics/rest/StatusITest.groovy). 0.11.0 was released with all the tests passing. There must be something else happening there.

**Comment by stefannegrea** [comment]
I restarted the build looked at the entire log. I see the `status` endpoint being deployed and I do not see anything in the logs about 404 on that endpoint.

@ppalaga, can you please link to that error in the last build?

**Comment by mtho11** [comment]
No one even trusts the travis integration tests anymore!

**Comment by mtho11** [comment]
Merging since the error has nothing to do with metrics but with:
testComplexScenario(org.hawkular.integration.test.HystrixCommandsITest)  Time elapsed: 14.476 sec  <<< ERROR!

**Comment by mtho11** [comment]
Merged #782

**Comment by mtho11** [comment]
This is something UI is waiting for.

**Pull request merged**
