### PR TITLE
HAWKULAR-135 Pinger is completely trusting each SSL certificate

### PR DESCRIPTION
**Pull request by marvec**

### CODE REVIEW

**Comment by marvec** [comment]
Ok, hawkular pinger was successfully built. The other module failed.

**Comment by ppalaga** [comment]
Welcome, Man in the Middle!

**Comment by ppalaga** [comment]
I checked locally that the tests are passing. The code is OK for the present state of the project, but we should not trust every cert in the future. I am OK with merging.

**Comment by ppalaga** [comment]
I added a follow-up task: https://issues.jboss.org/browse/HAWKULAR-203

**Pull request merged**
