### PR TITLE
Bump hawkular-charts version to include the change from HAWKULAR-213

### PR DESCRIPTION
**Pull request by pilhuhn**

### CODE REVIEW

**Comment by mtho11** [comment]
The bower.json rule:  "hawkular-charts": "^0.3.5" means that it will pull in all patch version > 0.3.5. So really isn,t necessary. When I build Hawkular locally I get the 0.3.9 hawkular-charts version.

**Comment by pilhuhn** [comment]
On 22 Jun 2015, at 18:20, Mike Thompson wrote:

> The bower.json rule:  "hawkular-charts": "^0.3.5" means that it will 
> pull in all patch version > 0.3.5. So really isn,t necessary. When I 
> build Hawkular locally I get the 0.3.9 hawkular-charts version.

I re-built master several times and it did not work.
Only when I explicitly requested 0.3.9 as in the patch.

**Comment by mtho11** [comment]
I'll merge for now since it can't hurt and evidently can help. But this is strange behaviour.

**Comment by mtho11** [comment]
A fun way to plan around with these rules visually: http://semver.npmjs.com/

**Pull request merged**
