### PR TITLE
HAWKULAR-979

### PR DESCRIPTION
**Pull request by cardosogabriel**

### CODE REVIEW

**Comment by jpkrohling** [comment]
When I click on "Edit" for one token, its size changes, and the screen gets a bit messy. Besides, the QR Code modal still has the QR Code not centered. Is that on purpose?

**Comment by jpkrohling** [comment]
Sorry, I see you commented on JIRA already :)

**Comment by cardosogabriel** [comment]
Sorry, I had aligned to the center only in the inspector here. Committed now :)

**Comment by mtho11** [comment]
@cardosogabriel @jpkrohling so the 'Don't Merge yet' is still in effect for this?

**Comment by jpkrohling** [comment]
Looks good to me!

**Pull request merged**
