### PR TITLE
HAWKULAR-444 - Clear token on timeout, so that background requests are blocked

### PR DESCRIPTION
**Pull request by jpkrohling**

### CODE REVIEW

**Comment by jpkrohling** [comment]
@mtho11 could you please review this one? Note that I added a new dependency on keycloak (which was a transitive dependency, through hawtio-oauth)

**Comment by jpkrohling** [comment]
It seems that @mtho11 is on PTO, so, could you please review this one, @vrockai ?

**Comment by vrockai** [comment]
looks good to me :thumbsup:

**Comment by mtho11** [comment]
Thanks vrockai!

**Pull request merged**
