### PR TITLE
Update the Dockerfile to Alpha4 and add more documentation

### PR DESCRIPTION
**Pull request by pilhuhn**
More docs.

Part of that could be replicated/moved into the Web site I guess.

### CODE REVIEW

**Comment by pilhuhn** [comment]
@vnugent If you have a better idea on how to (not) encode the hawkular version in the zip name, then let me know.

**Comment by pilhuhn** [comment]
Not sure why it is failing, but it looks like

**Comment by Jiri-Kremser** [comment]
> Not sure why it is failing, but it looks like some ...

nope, it's failing here https://travis-ci.org/hawkular/hawkular/builds/73890669#L1151
Don't ask me, why it's displayed only as a warning, if it fails the build

Perhaps, we should consider having some fast fail behavior in the mvn build, because it's hard to find the real issue..

**Comment by Jiri-Kremser** [comment]
>@vnugent I If you have a better idea on how to (not) encode the hawkular version in the zip name, then let me know.

what about:
```bash
/opt/hawkular-*-SNAPSHOT/bin/add-user.sh hawkularadmin hawkularadmin --silent
...
CMD ["/opt/hawkular-*-SNAPSHOT/bin/standalone.sh","-b","0.0.0.0","-bmanagement","0.0.0.0","-Djboss.server.data.dir=/opt/data"]

```

or 
```bash
ENV version `curl -Ls https://raw.githubusercontent.com/hawkular/hawkular/master/pom.xml | grep "^  <version>" | sed -e "s;  <version>\([0-9a-zA-Z\.\-]*\)</version>;\1;"`
do something with $version
```
?

The second approach is more risky because GitHub sometimes denies the requests because of their REST API limits.

**Comment by vnugent** [comment]
In the Hawkular ci project I pulled mvn logic out of Dockerfile and put it in a bash script

https://github.com/RedHatQE/hawkular-docker/blob/master/build.sh

**Pull request merged**
