### PR TITLE
HAWKULAR-372 - adding special origins for PhantomJS browser

### PR DESCRIPTION
**Pull request by Jiri-Kremser**
ui-services REST tests need it to work

### CODE REVIEW

**Comment by Jiri-Kremser** [comment]
@jpkrohling could you please review?

**Comment by jpkrohling** [comment]
You don't need this for the main realm file, shipped with the "production" profile, right? Only with the "dev" version, I assume. If so, it looks good to me.

**Comment by Jiri-Kremser** [comment]
yes, we run the tests only against the dev instance, because the jdoe is assumed

**Comment by jpkrohling** [comment]
Looks good to me :)

**Pull request merged**
