### PR TITLE
HAWKULAR-454 - Accounts 1.0.12.Final and required changes

### PR DESCRIPTION
**Pull request by jpkrohling**

### CODE REVIEW

**Comment by jpkrohling** [comment]
@ppalaga , I had problems with src-deps, but I wanted to send this PR anyway, to see if it looks good to you. 

@mtho11 , could you also check if this PR fixes the login issue?

**Comment by mtho11** [comment]
Wow, the build time really went up.

**Comment by mtho11** [comment]
Issues: http://fpaste.org/265243/44181201/

and this:

WebSocket connection to 'ws://localhost:8080/hawkular/feed-comm/ui/ws' failed: Error during WebSocket handshake: Unexpected response code: 404

**Comment by jpkrohling** [comment]
About the build time: it seems that the current master has taken 17 minutes already. So, it's not a problem in this PR.

**Comment by jpkrohling** [comment]
PR updated with changes to the versions of Agent, Bus and Command Gateway. 

@jmazzitelli , could you please check this as well, specially to verify that I haven't missed any component update?

**Comment by jmazzitelli** [comment]
This looks good.

**Comment by ppalaga** [comment]
lgtm

**Pull request merged**
