### PR TITLE
Hawkular Alerts 1.0.0.Final, HWKALERTS-133

### PR DESCRIPTION
**Pull request by jshaughn**
- bump to final version
- add CommandEvenListener to hawkular-listeners jar

### CODE REVIEW

**Comment by jshaughn** [comment]
@ppalaga please review and merge.

**Comment by ppalaga** [comment]
@jshaughn the first review round finished.

**Comment by jshaughn** [comment]
@ppalaga Thanks, please merge so hawkular is up to 1.0.0 of alerts for alpha10 release.

**Comment by ppalaga** [comment]
b9584e9 is OK to merge after it passes CI. Thanks @jshaughn !

**Pull request merged**
