### PR TITLE
Upgrade alerts 0.4.x

### PR DESCRIPTION
**Pull request by lucasponce**
Main tasks on this PR:
- Upgrade to Alerts 0.4.x.
- Upgrade to ui-services 0.8.2.
- Refactor UI services with new Alerts API.
- Add context support on triggers and conditions.

Please, @mtho11 and @jshaughn take a look on the PR to continue with other UI Alerts related tasks.

Thanks,
Lucas

### CODE REVIEW

**Comment by jshaughn** [comment]
LGTM!  The units should improve things for the end user.

**Comment by mtho11** [comment]
LGTM. The context and description fields are leap forward!

**Comment by lucasponce** [comment]
Hi,
Travis is not happy, but I can not identify if the issue is due alerts or another thing.
@mtho11 if you have rights, can you re-launch the ci ?
Thanks

**Comment by mtho11** [comment]
Merged #473

**Pull request merged**
