### PR TITLE
Fix Typescript tslint error: 

### PR DESCRIPTION
**Pull request by mtho11**
[gulp-tslint] error accessPortal/ts/accessPortalPlugin.ts[44, 26]: missing radix parameter

### CODE REVIEW

**Comment by mtho11** [comment]
I'll wait to merge this until after the build is fixed.

**Comment by mtho11** [comment]
Yes,  this is the original error:
[ERROR] plugins/accessPortal/ts/accessPortalPlugin.ts(43,35): error TS2345: Argument of type 'number' is not assignable to parameter of type 'string'.

Looks like I pasted the radix error above (incorrectly) instead of the original. The missing radix looks to be a bug in the typescript definition files because the radix is optional:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt

**Comment by jpkrohling** [comment]
I sent a new PR for fixing this issue (see #419) . I think this PR could be then closed.

**Comment by mtho11** [comment]
Close due to fix in #419

**Pull request closed without merging**
