### PR TITLE
Hawkular 530

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by ppalaga** [comment]
@ammendonca, let's see if adding origin-repository.jboss.org repo to Travis settings.xml helps for now.

**Comment by ppalaga** [comment]
If this one passes Travis, it will be a replacement for https://github.com/hawkular/hawkular/pull/417

**Comment by ppalaga** [comment]
It fails on Inventory integration tests

**Comment by ppalaga** [comment]
Do not merge yet, this is waiting for https://github.com/hawkular/hawkular-inventory/pull/153

**Comment by ppalaga** [comment]
@mtho11 could you please review the original commit of @ammendonca ? All the other commits should be sufficiently validated by the CI.

**Comment by mtho11** [comment]
LGTM.

**Pull request merged**
