### PR TITLE
Hwkinvent 78

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by ppalaga** [comment]
@metlos could you please review and eventually merge?

**Comment by ppalaga** [comment]
Failed because it depends on https://github.com/hawkular/hawkular-inventory/pull/101

**Comment by metlos** [comment]
Shouldn't the last commit upgrade inventory to 0.1.0.Final?

**Comment by metlos** [comment]
Oh, it does :) Only the commit message is wrong.

**Comment by ppalaga** [comment]
@metlos fixed the last message. Sorry.

**Comment by metlos** [comment]
lgtm. This needs to go inline with a new release of agent that will adapt to the same changes accordingly.

**Pull request merged**
