### PR TITLE
HWKINVENT-69 | inventory ping integration test

### PR DESCRIPTION
**Pull request by pavolloffay**

### CODE REVIEW

**Comment by ppalaga** [comment]
@pavolloffay should this not better go to hawkular:dev/inventory-0.2.0.Alpha1 branch?

**Comment by pavolloffay** [comment]
yes, but it should also work on master. 

I will put it into 0.2.0.Alpha1,

**Comment by ppalaga** [comment]
Yes, I agree this would also work on master, but because we do a lot of work in dev/inventory-0.2.0.Alpha1, it is just safer to send all changes there just to avoid conflicts.

**Comment by pavolloffay** [comment]
See https://github.com/hawkular/hawkular/pull/334

**Pull request closed without merging**
