### PR TITLE
HAWKULAR-94 - Customize standalone.conf.bat like we do for standalone.conf

### PR DESCRIPTION
**Pull request by jpkrohling**

### CODE REVIEW

**Comment by jpkrohling** [comment]
Please, do not merge it yet. License check failure. I'll amend the commit and update the PR.

**Comment by jpkrohling** [comment]
This PR is ready to be merged.

**Comment by mtho11** [comment]
@jshaughn can you validate this?

**Comment by mtho11** [comment]
@jshaughn and mark the Jira as resolved as well, if it works.

**Pull request merged**
