### PR TITLE
[HAWKULAR-299] A resource disappearing asynchronously while traits publisher

### PR DESCRIPTION
**Pull request by metlos**
tries to write to it is a valid scenario and should not result in an
unhandled exception.

### CODE REVIEW

**Comment by ppalaga** [comment]
Why are all Inventory exceptions unchecked?

**Comment by metlos** [comment]
Why are all JPA exceptions unchecked?

**Comment by ppalaga** [comment]
@metlos sorry, I do neither know nor have found quickly enough why JPA exceptions are unchecked. Could you please explain as shortly as possible?

**Comment by ppalaga** [comment]
@metlos could you please {{s/HAWKULAR-255/HAWKULAR-299/}} in the commit message?

**Comment by metlos** [comment]
Well, that is quite a complicate question to answer and is of course partially a matter of taste.

But the reasoning behind not using checked exceptions is that rarely the caller has any reasonable way of handling the exception. So by using a documented unchecked exception you give the caller the OPTION to handle the exception but you do not force them to do so if they have no way of sensibly handling it.

http://docs.oracle.com/javase/tutorial/essential/exceptions/runtime.html

IMHO, `EntityNotFoundException` is one that the caller cannot be expected to reasonably recover from - they asked for something which isn't there. A typical catch block for such exception would be to merely rethrow it, so it doesn't make sense to make a checked exception.

**Comment by metlos** [comment]
Corrected the JIRA number.

**Comment by ppalaga** [comment]
@metlos thanks for the explanation. For me as an API user, it is a disadvantage to have to search for unchecked exceptions that I could want to handle. Moreover, there is a very good chance that I'll miss future changes in thrown exceptions. With checked exceptions the compiler would fail or at least warn me on any change.

**Comment by ppalaga** [comment]
I find the change OK to merge once the latest version passes CI.

**Comment by metlos** [comment]
CI passed.

**Pull request merged**
