### PR TITLE
Prepare pinger and availcreator for Metrics 0.3.5

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by ppalaga** [comment]
@jmazzitelli could you please review?

**Comment by jmazzitelli** [comment]
don't forget that we need to rebase this on current master since some changes (in assembly build and in agent) are needed there

**Comment by ppalaga** [comment]
> we need to rebase this on current master

This ATM *is* on top of the current master.

**Comment by pilhuhn** [comment]
Well, it says "into hawkular:metrics-next" at the top.

**Pull request merged**
