### PR TITLE
Hawkular 1056

### PR DESCRIPTION
**Pull request by karelhala**
Fix encoding of equals sign in child resources, which broke children tree. And fix loading of metrics.

Fix refreshing of graphs, where axis were not refreshed at all.

### CODE REVIEW

**Comment by pilhuhn** [comment]
I just had a quick look (checkout that pr, gulp watch-server) and it did not work for me.
Will check with a clean build later.

**Comment by karelhala** [comment]
>I just had a quick look (checkout that pr, gulp watch-server) and it did not work for me.
Will check with a clean build later.

You have to checkout from master, there was problem with changing path for builded console, hence https://github.com/hawkular/hawkular/pull/874/commits/8a4ffbc1212db4227a329ebe9c81b9aeb5127de1#diff-a5994c7790a38e73bf5131c77efed2bbL47

**Comment by mtho11** [comment]
@karelhala What is the status on this one?

**Comment by mtho11** [comment]
Closing this one since the UI is moving repos. It won't be valid on the new repo anyway. New UI repo: https://github.com/hawkular/hawkular-ui

**Pull request closed without merging**
