### PR TITLE
HAWKULAR-323 Add log level system variables

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by ppalaga** [comment]
[Don't Merge Yet]

**Comment by jmazzitelli** [comment]
I think this is fine. I don't consider this polluting standalone.xml - we are adding these categories already - its just the value we are setting it to can be overridden with runtime system properties. I am +1 on this. anyone else have opinions?

**Comment by tsegismont** [comment]
Looks good to me as well. The system property switch is nice as you can use it for a one time debug session, whereas changes with the CLI are persisted and need to be rolled back.

**Comment by ppalaga** [comment]
There seems to be enough consensus in this matter. @pilhuhn could you please merge once the last rebase passes CI?

**Pull request merged**
