### PR TITLE
Hawkular Data Mining integration

### PR DESCRIPTION
**Pull request by pavolloffay**
Hawkular Data Mining integration into Hawkular.

Please do not merge yet!

### CODE REVIEW

**Comment by pavolloffay** [comment]
The build is failing (The server failed to start: Managed server was not started within [360]) but local build passes without any problems.

**Comment by mtho11** [comment]
@pavolloffay I assume this should be closed since the UI is moving repos: https://github.com/hawkular/hawkular-ui

**Comment by pavolloffay** [comment]
@mtho11 this does not include only UI part but also the whole integration of Data mining. As this repo is stating for comunity distribution I would like to keep it.

**Comment by stefannegrea** [comment]
Closing this because it is no longer relevant.

**Pull request closed without merging**
