### PR TITLE
Upgrade to hawkular-parent 18

### PR DESCRIPTION
**Pull request by ppalaga**
@Jiri-Kremser could you please review?

### CODE REVIEW

**Comment by Jiri-Kremser** [comment]
@ppalaga travis failed with some deployment issues, I've re-run the build. Let's see what happens now. Perhaps the dependencies need to be changed also somewhere else (?)

**Comment by ppalaga** [comment]
@Jiri-Kremser I have seen that fail and wondered about it. It is passing here on my laptop locally.

**Comment by ppalaga** [comment]
@Jiri-Kremser we should perhaps turn agent off in itest profile to exclude one important source of non-reproducibility.

**Comment by Jiri-Kremser** [comment]
This hawkular branch depends on inventory-snapshot, so I think the issue is caused by this PR (https://github.com/hawkular/hawkular-inventory/pull/117), @pavolloffay could you please look into the itests?

**Comment by pavolloffay** [comment]
There is a pull request for HWKINVENT-90 on hawkular/hawkular https://github.com/hawkular/hawkular/pull/327 .

**Comment by ppalaga** [comment]
I merged #327 and restarted Travis here.

**Pull request merged**
