### PR TITLE
[HKWINVENT-24] WIP - port pinger to new inventory bus

### PR DESCRIPTION
**Pull request by metlos**
This builds on top of #69 and re-adds the ability of the inventory to inform about changes inside over the bus.

There are still some problems though, so don't merge yet.

### CODE REVIEW

**Comment by metlos** [comment]
This depends on PR https://github.com/hawkular/hawkular-inventory/pull/46 in inventory and on the ability of inventory to create entities and add properties to them at the same time (which is pending).

Once both of those features are in, this should theoretically work.

**Comment by mtho11** [comment]
Can you start the pinger immediately, so we start collecting data sooner than collection period. We would like to have the UI show results faster than the current collection period.

**Comment by metlos** [comment]
I'm glad I managed to hack around the pinger enough to make it receive the new inventory messages, but I see no deeper into it ;)

@pilhuhn would you be able to comment on @mtho11's request?

**Comment by Jiri-Kremser** [comment]
Closing this pr on behalf of PR #75 (it's based on it)

**Pull request closed without merging**
