### PR TITLE
HAWKULAR-226 Display traits from a URL

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by ppalaga** [comment]
@mtho11 could you please review?

**Comment by ppalaga** [comment]
@mtho11 I have just rebased once again on top of the current master and force-pushed.

**Comment by ppalaga** [comment]
The last push ending with dd31630 is fixing the tests and typescript syntax. I hope it will pass the CI.

**Comment by mtho11** [comment]
Merged #357

**Pull request merged**
