### PR TITLE
HAWKULAR-844

### PR DESCRIPTION
**Pull request by jsanda**
Note that this should not be merged until https://github.com/hawkular/hawkular-bus/pull/53 is merged and we have a new release of hawkular-bus.

### CODE REVIEW

**Comment by jsanda** [comment]
@ppalaga would you mind reviewing this?

**Comment by ppalaga** [comment]
@jsanda as I already said the private chat, I am not particularly happy about Hawkular main being on WF 10 before, inventory, cmdgw, agent, etc. were upgraded and tested. However I know that this blocks your other work and I do not want to stand in a way.

I have no time ATM to build and smoke test this branch. Would you please find somebody to do that?

**Comment by jsanda** [comment]
As it turns out, I don't think this blocks a stand alone metrics + alerts distro because. It won't use a full hawkular server, just metrics, alerts, and the bus shared library.

**Comment by pilhuhn** [comment]
What is the status of this @jsanda and @ppalaga ?

**Comment by ppalaga** [comment]
@pilhuhn I do not think I can say something relevant. @jsanda ?

**Comment by jsanda** [comment]
I do not think this PR is relevant any more. I think that we can close it.

**Pull request closed without merging**
