### PR TITLE
HAWKULAR-521 - Accounts release

### PR DESCRIPTION
**Pull request by jpkrohling**

### CODE REVIEW

**Comment by ppalaga** [comment]
The PR in itself is fine, I have built and made a few clicks in the UI. But could you please change the commit message to something more appropriate? This commit is not a release of accounts. For me it is an upgrade to Accounts 1.0.10.Final. WDYT?

**Comment by jpkrohling** [comment]
Changed :-) The commit itself is the same, just "git commit --ammend" to change the commit message.

**Comment by ppalaga** [comment]
My wish was to name the version 1.0.10.Final. I hope for it next time ;).

**Comment by jpkrohling** [comment]
Got it. Will do it next time.

**Comment by ppalaga** [comment]
BTW, Juca, have you sent the upgade to all consuming components? http://www.hawkular.org/docs/dev/development.html#component-dependencies

**Comment by jpkrohling** [comment]
Good point, I haven't. Will send it! Thanks for reminding me

**Pull request merged**
